// CRUD Productos
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const READ_PRODUCT = "READ_PRODUCT";
export const READ_PRODUCT_SUCCESS = "READ_PRODUCT_SUCCESS";
export const READ_PRODUCT_ERROR = "READ_PRODUCT_ERROR";

export const SET_UPDATE_PRODUCT = "SET_UPDATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

// CRUD usuarios
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const READ_USER = "READ_USER";
export const READ_USER_SUCCESS = "READ_USER_SUCCESS";
export const READ_USER_ERROR = "READ_USER_ERROR";

export const SET_UPDATE_USER = "SET_UPDATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

// CRUD Carrito
export const CREATE_CAR = "CREATE_CAR";
export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS";
export const CREATE_CAR_ERROR = "CREATE_CAR_ERROR";

export const READ_CAR = "READ_CAR";
export const READ_CAR_SUCCESS = "READ_CAR_SUCCESS";
export const READ_CAR_ERROR = "READ_CAR_ERROR";

export const SET_UPDATE_CAR = "SET_UPDATE_CAR";
export const UPDATE_CAR = "UPDATE_CAR";
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS";
export const UPDATE_CAR_ERROR = "UPDATE_CAR_ERROR";

export const DELETE_CAR = "DELETE_CAR";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR";

// Otros
export const LOGIN = "LOGIN";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SHOW_ALERT = "MOSTRAR_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
